language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: curso-github-cefire
  on: master
  skip_cleanup: true
  api_key:
    secure: gBj38CjeoemcG7Z3BlSPZtBxt90ffEnVuR8cNPoB0Zl2hHNLIDBsgfGwVMqndIIMxkNk0GRKARpIHm0VB6qELh1aEgiKcYFYKiX7oSpIx22MJc+M06V4J9fFYD6ISccHT6/rq6F432tX4znCE3RI/gOgsYbXCmS/mokQYtpLnIcG/Va1eid8fKuphhRozqZK13A5ndWHTv8ffTePP1PeENnWtuYhft4Hf+yrRu7dE+0KsMwy4Sf6d8q5oute4GBad4q9U+q7HBIa+Rqy+MiWCSOmG2xYyF0fPi8dBlSR/mkz3QejSlUpiBybFMzstnulk0SLid+Mb1SH7yMxkRLpt0USrpg5C7XURN5TUNXaST66BImUKlS55gfqfsmslZuljd8Q9B2Mj3OoJwUf6ieHNrb9769jv/J50sB58jeXSLWFqguzEIakpwcbUWpjy4nz1In1KHsWcUle3nD4/1dN6YjHYdEePuZNSMtNT5zOU0DUDX7mBK6a2jQhP21iCXLouZZf2IjE3niKhkDmFpJlfCOBX3CD7H/D2adHrJuHIy2CV9LQw+axd3JyARm84pttUELFuAjGF8t4NHcdfzZtRNkeFf8WPQu0l0uUxhCBjeKIAB5HJ1edvdfvsk0SgHw0mbn4vSSF5m6TVoQicZln2Vgn7M+zGmhxPvu0vw3EFo8=
